name: Publish on PR merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      # (see: https://docs.pypi.org/trusted-publishers/using-a-publisher/)
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.7"

      - name: Check if version is bumped
        id: check_version
        run: |
          eval $(uvx bumpver show --environ)
          if git tag -l | grep -q "^$PEP440_VERSION$"; then
            echo "Version $PEP440_VERSION already exists. Exiting."
            exit 1
          fi
          echo "::set-output name=version::$PEP440_VERSION"

      - name: Build package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Push tag
        env:
          VERSION: ${{ steps.check_version.outputs.version }}
        run: |
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.check_version.outputs.version }}
        run: |
          gh release create "$VERSION" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${VERSION}" \
              --generate-notes
