name: Create GitHub release
on:
  workflow_run:
    # This workflow is triggered when the "Publish on PR merge" workflow in `on-merge-to-main.yaml` is completed
    workflows: ["Publish on PR merge"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      # Cannot use `@actions/download-artifact` because it does not support downloading artifacts from a different workflow run
      # (see: https://github.com/dawidd6/action-download-artifact).
      - name: Download version info
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow_conclusion: success
          # Only one of pr, commit, branch, run_id can be specified
          run_id: ${{ github.event.workflow_run.id }}
          name: version-info
          path: .

      - name: Load version info
        id: version_info
        run: |
          VERSION_BUMPED=$(cat version_status.txt)
          VERSION=$(cat version.txt)
          echo "version_bumped=${VERSION_BUMPED}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout
        if: steps.version_info.outputs.version_bumped == 'true'
        uses: actions/checkout@v4

      - name: Push tag
        if: steps.version_info.outputs.version_bumped == 'true'
        env:
          VERSION: ${{ steps.version_info.outputs.version }}
        run: |
          git config --global user.email "57234880+duynguyen158@users.noreply.github.com"
          git config --global user.name "Duy Nguyen"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Create release
        if: steps.version_info.outputs.version_bumped == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version_info.outputs.version }}
        run: |
          gh release create "$VERSION" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${VERSION}" \
              --generate-notes