name: Run checks
on:
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/on-pull-request.yaml"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.2
      - name: Install dependencies
        run: poetry config virtualenvs.create false && poetry install --no-interaction
      - name: Check type
        run: mypy
      - name: Run tests
        run: pytest --cov=yootils/ tests/