name: Run checks
on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.3"
      - name: Remove .python-version
        run: rm -f .python-version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-groups --all-extras --python-preference only-system
      - name: Check formatting
        run: uvx ruff check
      - name: Check type
        run: uvx pyright
      - name: Run tests
        env:
          PYTHON_MAJOR_MINOR_VERSION: $(uv run python -V | grep -oE "[0-9]+\.[0-9]+")
        run: uv run pytest --cov=yootils/ tests/