name: Publish to PyPI
on:
  workflow_run:
    workflows: ["Create release"]
    types:
      - completed

jobs:
  publish-package:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}